# Generated by Django 6.0.2 on 2026-02-06 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_assignment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='title',
            new_name='name',
        ),
    ]
