# Generated by Django 6.0.2 on 2026-02-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_assignment', '0002_rename_title_menuitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='inventory',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
