# Generated by Django 6.0.2 on 2026-02-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_assignment', '0003_alter_menuitem_inventory_alter_menuitem_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('menu_item_name', models.CharField(max_length=255)),
                ('menu_item_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='inventory',
        ),
    ]
