# Generated by Django 6.0.2 on 2026-02-06 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_assignment', '0004_cart_remove_menuitem_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='username',
        ),
    ]
