# Generated by Django 6.0.2 on 2026-02-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_assignment', '0005_rename_user_cart_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='username',
            new_name='user_id',
        ),
    ]
