# Generated by Django 6.0.2 on 2026-02-06 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_assignment', '0007_order_alter_cart_user_id_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='api_assignment.order'),
        ),
    ]
